#!/usr/bin/env python3
"""
Extended training data for APEX ML FP Classifier.

Provides 150+ additional False Positive examples across all vulnerability
categories to fix class imbalance (was 319 TP vs 49 FP).

Categories covered:
  - Prepared Statements / ORM (20)
  - Type Cast / Validation (15)
  - Output Sanitization (15)
  - Framework Validation (12)
  - Comments / Dead Code (10)
  - Safe Headers (8)
  - Safe Crypto / Hash (8)
  - Config / Constants (6)
  - Custom Sanitizer Wrappers (8)
  - Safe File Operations (8)
  - Auth / Access Control (6)
  - Safe SSRF (5)
  - Safe Deserialization (5)
  - Race Condition FPs (5)
  - Log / Info Disclosure FPs (6)
  - XSS False Positives (10)
  - Path Traversal Safe (5)
  - Miscellaneous FPs (8)
"""


def get_extended_fp_examples():
    """Return 160+ FP training examples for ML classifier balance."""
    return [
        # ======================================================================
        # PREPARED STATEMENTS / ORM (20 examples)
        # ======================================================================
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$stmt = $pdo->prepare("SELECT name FROM users WHERE id = :id"); $stmt->bindValue(":id", $_GET["id"], PDO::PARAM_INT);',
         'line': 12, 'file': 'user_model.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '65%',
         'code': '$result = $wpdb->get_results($wpdb->prepare("SELECT * FROM {$wpdb->posts} WHERE post_author = %d", $user_id));',
         'line': 25, 'file': 'wp-includes/post.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '60%',
         'code': '$users = User::whereIn("id", $request->input("ids"))->get();',
         'line': 18, 'file': 'app/Http/Controllers/UserController.php'},
        {'type': 'SQL Injection', 'severity': 'MEDIUM', 'confidence': '55%',
         'code': '$count = DB::table("orders")->where("status", "=", $request->status)->count();',
         'line': 30, 'file': 'app/Http/Controllers/OrderController.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '65%',
         'code': '$stmt = $mysqli->prepare("UPDATE users SET email = ? WHERE id = ?"); $stmt->bind_param("si", $email, $id);',
         'line': 42, 'file': 'update_profile.php'},
        {'type': 'SQL Injection', 'severity': 'MEDIUM', 'confidence': '60%',
         'code': '$post = Post::findOrFail($request->input("post_id"));',
         'line': 15, 'file': 'app/Http/Controllers/PostController.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$stmt = $db->prepare("DELETE FROM sessions WHERE token = ?"); $stmt->execute([$_COOKIE["session_token"]]);',
         'line': 8, 'file': 'logout.php'},
        {'type': 'SQL Injection', 'severity': 'MEDIUM', 'confidence': '55%',
         'code': '$items = $this->db->select("products")->where("category_id", $this->input->get("cat"))->get();',
         'line': 20, 'file': 'application/controllers/Shop.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '65%',
         'code': '$qb = $em->createQueryBuilder(); $qb->select("u")->from("User", "u")->where("u.email = :email")->setParameter("email", $email);',
         'line': 35, 'file': 'src/Repository/UserRepository.php'},
        {'type': 'SQL Injection', 'severity': 'MEDIUM', 'confidence': '60%',
         'code': '$results = Yii::$app->db->createCommand("SELECT * FROM items WHERE id=:id", [":id" => $id])->queryAll();',
         'line': 22, 'file': 'controllers/ItemController.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$stmt = $pdo->prepare("INSERT INTO audit_log (action, user_id, ip) VALUES (?, ?, ?)"); $stmt->execute([$action, $uid, $_SERVER["REMOTE_ADDR"]]);',
         'line': 50, 'file': 'lib/audit.php'},
        {'type': 'SQL Injection', 'severity': 'MEDIUM', 'confidence': '55%',
         'code': 'Product::where("name", "like", "%" . $request->search . "%")->paginate(20);',
         'line': 28, 'file': 'app/Http/Controllers/SearchController.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '65%',
         'code': '$row = $db->fetchAssoc("SELECT * FROM config WHERE `key` = ?", [$_GET["setting"]]);',
         'line': 14, 'file': 'admin/settings.php'},
        {'type': 'SQL Injection', 'severity': 'MEDIUM', 'confidence': '60%',
         'code': '$this->db->where("user_id", $this->session->userdata("user_id"))->delete("cart");',
         'line': 33, 'file': 'application/controllers/Cart.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$sth = $dbh->prepare("SELECT balance FROM accounts WHERE account_no = :acct"); $sth->execute([":acct" => $_POST["account"]]);',
         'line': 18, 'file': 'banking/transfer.php'},
        {'type': 'SQL Injection', 'severity': 'MEDIUM', 'confidence': '55%',
         'code': '$records = CActiveRecord::model("Log")->findAllByAttributes(["type" => $type]);',
         'line': 40, 'file': 'protected/controllers/LogController.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '65%',
         'code': '$stmt = pg_prepare($conn, "my_query", "SELECT * FROM users WHERE username = $1"); $result = pg_execute($conn, "my_query", [$_POST["user"]]);',
         'line': 10, 'file': 'pg_auth.php'},
        {'type': 'SQL Injection', 'severity': 'MEDIUM', 'confidence': '60%',
         'code': '$query = $this->getEntityManager()->createQuery("SELECT u FROM App\\Entity\\User u WHERE u.role = :role"); $query->setParameter("role", $role);',
         'line': 45, 'file': 'src/Repository/UserRepository.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '65%',
         'code': 'db_select("node", "n")->fields("n")->condition("n.uid", $uid, "=")->execute();',
         'line': 20, 'file': 'modules/custom/custom.module'},
        {'type': 'SQL Injection', 'severity': 'MEDIUM', 'confidence': '55%',
         'code': 'TableRegistry::getTableLocator()->get("Articles")->find()->where(["author_id" => $this->request->getData("author")])->all();',
         'line': 30, 'file': 'src/Controller/ArticlesController.php'},

        # ======================================================================
        # TYPE CAST / VALIDATION (15 examples)
        # ======================================================================
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$page = max(1, (int)$_GET["page"]); $db->query("SELECT * FROM posts LIMIT " . (($page-1)*20) . ", 20");',
         'line': 5, 'file': 'blog.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '65%',
         'code': '$limit = abs(intval($_GET["limit"])); $db->query("SELECT * FROM items LIMIT " . $limit);',
         'line': 10, 'file': 'api/list.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'MEDIUM', 'confidence': '55%',
         'code': 'echo "Page " . (int)$_GET["page"] . " of " . $total;',
         'line': 15, 'file': 'paginator.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '70%',
         'code': 'if (ctype_digit($_GET["id"])) { $db->query("SELECT * FROM users WHERE id=" . $_GET["id"]); }',
         'line': 8, 'file': 'profile.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '65%',
         'code': '$id = filter_input(INPUT_GET, "id", FILTER_VALIDATE_INT); if ($id !== false) { $db->query("SELECT * FROM items WHERE id=$id"); }',
         'line': 12, 'file': 'item.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'MEDIUM', 'confidence': '50%',
         'code': 'echo "Total: " . number_format(floatval($_POST["amount"]), 2);',
         'line': 20, 'file': 'checkout.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '65%',
         'code': 'settype($input_id, "integer"); $result = $db->query("SELECT * FROM records WHERE id=" . $input_id);',
         'line': 14, 'file': 'record.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '70%',
         'code': 'if (is_numeric($_POST["price"])) { $db->query("UPDATE products SET price=" . floatval($_POST["price"]) . " WHERE id=$pid"); }',
         'line': 25, 'file': 'admin/product.php'},
        {'type': 'Command Injection', 'severity': 'HIGH', 'confidence': '75%',
         'code': '$count = (int)$_GET["count"]; exec("head -n " . $count . " /var/log/app.log", $output);',
         'line': 8, 'file': 'admin/logs.php'},
        {'type': 'SQL Injection', 'severity': 'MEDIUM', 'confidence': '55%',
         'code': 'if (preg_match("/^[0-9]+$/", $_GET["id"])) { $db->query("SELECT * FROM users WHERE id=" . $_GET["id"]); }',
         'line': 10, 'file': 'user.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '60%',
         'code': '$sort = in_array($_GET["sort"], ["name", "date", "price"]) ? $_GET["sort"] : "date"; $db->query("SELECT * FROM items ORDER BY " . $sort);',
         'line': 18, 'file': 'catalog.php'},
        {'type': 'Open Redirect', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$url = filter_var($_GET["redirect"], FILTER_VALIDATE_URL); if ($url && parse_url($url, PHP_URL_HOST) === "example.com") { header("Location: " . $url); }',
         'line': 5, 'file': 'redirect.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'MEDIUM', 'confidence': '55%',
         'code': '$status = in_array($_GET["s"], ["active", "inactive", "pending"]) ? $_GET["s"] : "active"; echo "<span>$status</span>";',
         'line': 22, 'file': 'status.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '65%',
         'code': '$year = (int)$_GET["year"]; $month = (int)$_GET["month"]; $db->query("SELECT * FROM events WHERE YEAR(date)=$year AND MONTH(date)=$month");',
         'line': 30, 'file': 'calendar.php'},
        {'type': 'Path Traversal', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$lang = preg_match("/^[a-z]{2}$/", $_GET["lang"]) ? $_GET["lang"] : "en"; include("lang/" . $lang . ".php");',
         'line': 3, 'file': 'i18n.php'},

        # ======================================================================
        # OUTPUT SANITIZATION (15 examples)
        # ======================================================================
        {'type': 'Cross-Site Scripting', 'severity': 'HIGH', 'confidence': '70%',
         'code': 'echo htmlspecialchars($_POST["comment"], ENT_QUOTES, "UTF-8");',
         'line': 40, 'file': 'comment.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'MEDIUM', 'confidence': '55%',
         'code': 'echo "<input type=\"text\" value=\"" . htmlentities($name, ENT_QUOTES) . "\">";',
         'line': 25, 'file': 'form.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'MEDIUM', 'confidence': '50%',
         'code': 'echo strip_tags($_POST["bio"]);',
         'line': 30, 'file': 'profile.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'HIGH', 'confidence': '65%',
         'code': '$clean = wp_kses($_POST["content"], $allowed_html); echo $clean;',
         'line': 35, 'file': 'wp-content/themes/theme/single.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'MEDIUM', 'confidence': '55%',
         'code': 'echo esc_html($title) . " - " . esc_html($subtitle);',
         'line': 10, 'file': 'wp-content/themes/theme/header.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'HIGH', 'confidence': '60%',
         'code': 'printf("<a href=\"%s\">%s</a>", esc_url($link), esc_html($text));',
         'line': 18, 'file': 'wp-content/themes/theme/nav.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'MEDIUM', 'confidence': '55%',
         'code': '$purifier = new HTMLPurifier($config); $clean = $purifier->purify($_POST["html_content"]); echo $clean;',
         'line': 20, 'file': 'editor.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'HIGH', 'confidence': '65%',
         'code': 'echo json_encode(["name" => $name, "email" => $email], JSON_HEX_TAG | JSON_HEX_QUOT);',
         'line': 15, 'file': 'api/user.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'MEDIUM', 'confidence': '50%',
         'code': 'echo "<option value=\"" . (int)$id . "\" " . ($id == $selected ? "selected" : "") . ">" . htmlspecialchars($label) . "</option>";',
         'line': 28, 'file': 'components/select.php'},
        {'type': 'Command Injection', 'severity': 'HIGH', 'confidence': '75%',
         'code': '$pattern = escapeshellarg($_POST["search"]); $cmd = escapeshellcmd("grep -r $pattern /var/www/logs/"); exec($cmd, $output);',
         'line': 12, 'file': 'admin/log_search.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'MEDIUM', 'confidence': '55%',
         'code': '<?= e($user->name) ?> - <?= e($user->email) ?>',
         'line': 5, 'file': 'resources/views/user/show.blade.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'HIGH', 'confidence': '60%',
         'code': '{{ $title }} {{ $description }}',
         'line': 8, 'file': 'resources/views/page.blade.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '65%',
         'code': '$safe_name = mysqli_real_escape_string($conn, $_POST["name"]); $db->query("SELECT * FROM users WHERE name=\'" . $safe_name . "\'");',
         'line': 22, 'file': 'search.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'MEDIUM', 'confidence': '50%',
         'code': 'echo DLEPlugins::Check(dle_filter($name));',
         'line': 15, 'file': 'engine/modules/show.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$safe = addslashes($_POST["search"]); $result = $db->query("SELECT * FROM articles WHERE title LIKE \'%$safe%\'");',
         'line': 18, 'file': 'search_articles.php'},

        # ======================================================================
        # FRAMEWORK VALIDATION (12 examples)
        # ======================================================================
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '65%',
         'code': '$data = $request->validate(["email" => "required|email", "age" => "required|integer|min:1|max:150"]); User::create($data);',
         'line': 20, 'file': 'app/Http/Controllers/RegisterController.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'MEDIUM', 'confidence': '55%',
         'code': '$validated = $request->validate(["title" => "required|string|max:200"]); return view("post", $validated);',
         'line': 15, 'file': 'app/Http/Controllers/PostController.php'},
        {'type': 'SQL Injection', 'severity': 'MEDIUM', 'confidence': '60%',
         'code': 'Validator::make($request->all(), ["id" => "required|integer", "status" => "required|in:active,inactive"])->validate();',
         'line': 10, 'file': 'app/Http/Controllers/StatusController.php'},
        {'type': 'File Inclusion', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$validated = $request->validate(["template" => "required|in:header,footer,sidebar"]); include("templates/" . $validated["template"] . ".php");',
         'line': 8, 'file': 'app/Http/Controllers/TemplateController.php'},
        {'type': 'SQL Injection', 'severity': 'MEDIUM', 'confidence': '55%',
         'code': '$form = $this->createForm(UserType::class); $form->handleRequest($request); if ($form->isValid()) { $em->persist($form->getData()); }',
         'line': 25, 'file': 'src/Controller/UserController.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'MEDIUM', 'confidence': '50%',
         'code': '$this->form_validation->set_rules("username", "Username", "required|alpha_numeric|max_length[50]"); if ($this->form_validation->run()) { $name = $this->input->post("username"); }',
         'line': 12, 'file': 'application/controllers/User.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '60%',
         'code': '$request->validate(["order_id" => "required|exists:orders,id", "quantity" => "required|integer|min:1"]);',
         'line': 18, 'file': 'app/Http/Controllers/OrderController.php'},
        {'type': 'Unsafe File Upload', 'severity': 'HIGH', 'confidence': '75%',
         'code': '$request->validate(["avatar" => "required|image|mimes:jpeg,png,gif|max:2048"]); $path = $request->file("avatar")->store("avatars");',
         'line': 22, 'file': 'app/Http/Controllers/ProfileController.php'},
        {'type': 'SQL Injection', 'severity': 'MEDIUM', 'confidence': '55%',
         'code': '$model = new LoginForm(); $model->load(Yii::$app->request->post()); if ($model->validate()) { $model->login(); }',
         'line': 15, 'file': 'controllers/SiteController.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'MEDIUM', 'confidence': '50%',
         'code': 'check_admin_referer("update_settings"); $value = sanitize_text_field($_POST["option_value"]); update_option("my_setting", $value);',
         'line': 30, 'file': 'wp-content/plugins/my-plugin/admin.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '65%',
         'code': '$validated = $this->validate($request, ["search" => "string|max:100"]); $results = Product::search($validated["search"])->get();',
         'line': 10, 'file': 'app/Http/Controllers/SearchController.php'},
        {'type': 'Unsafe File Upload', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$request->validate(["document" => "required|file|mimetypes:application/pdf|max:10240"]); $request->file("document")->storeAs("docs", Str::uuid() . ".pdf");',
         'line': 28, 'file': 'app/Http/Controllers/DocumentController.php'},

        # ======================================================================
        # COMMENTS / DEAD CODE (10 examples)
        # ======================================================================
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '75%',
         'code': '// $result = $db->query("SELECT * FROM users WHERE name=\'" . $_POST["name"] . "\'");',
         'line': 10, 'file': 'deprecated.php'},
        {'type': 'Code Injection', 'severity': 'CRITICAL', 'confidence': '85%',
         'code': '/* eval($_POST["cmd"]); // REMOVED: security vulnerability found in audit */',
         'line': 5, 'file': 'legacy_admin.php'},
        {'type': 'Command Injection', 'severity': 'CRITICAL', 'confidence': '90%',
         'code': '# system($_GET["cmd"]); // TODO: remove this debug code',
         'line': 20, 'file': 'debug.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'HIGH', 'confidence': '70%',
         'code': '// echo $_GET["msg"]; // replaced with proper escaping below',
         'line': 15, 'file': 'messages.php'},
        {'type': 'File Inclusion', 'severity': 'HIGH', 'confidence': '80%',
         'code': '/** include($_GET["module"]); // old dynamic include, now uses whitelist */',
         'line': 8, 'file': 'router.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '70%',
         'code': '/*\n$db->query("DELETE FROM users WHERE id=" . $_GET["id"]);\n*/',
         'line': 30, 'file': 'admin_users.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'MEDIUM', 'confidence': '60%',
         'code': '// echo "<script>alert(" . $user_input . ")</script>"; // XSS test removed',
         'line': 50, 'file': 'test_page.php'},
        {'type': 'Command Injection', 'severity': 'HIGH', 'confidence': '80%',
         'code': '// passthru("cat " . $_GET["file"]); // disabled for security',
         'line': 12, 'file': 'view_file.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '70%',
         'code': 'if (false) { $db->query("SELECT * FROM " . $_GET["table"]); } // dead code',
         'line': 25, 'file': 'query_builder.php'},
        {'type': 'Code Injection', 'severity': 'CRITICAL', 'confidence': '90%',
         'code': '// assert($_POST["expr"]); // SECURITY: removed per audit finding #42',
         'line': 18, 'file': 'evaluator.php'},

        # ======================================================================
        # SAFE HEADERS (8 examples)
        # ======================================================================
        {'type': 'HTTP Header Injection', 'severity': 'HIGH', 'confidence': '70%',
         'code': 'header("Content-Type: text/html; charset=UTF-8");',
         'line': 1, 'file': 'index.php'},
        {'type': 'HTTP Header Injection', 'severity': 'HIGH', 'confidence': '65%',
         'code': 'header("X-Content-Type-Options: nosniff");',
         'line': 2, 'file': 'security_headers.php'},
        {'type': 'HTTP Header Injection', 'severity': 'HIGH', 'confidence': '70%',
         'code': 'header("Cache-Control: no-store, no-cache, must-revalidate");',
         'line': 3, 'file': 'api_response.php'},
        {'type': 'HTTP Header Injection', 'severity': 'MEDIUM', 'confidence': '60%',
         'code': 'header("Strict-Transport-Security: max-age=31536000; includeSubDomains");',
         'line': 4, 'file': 'security.php'},
        {'type': 'HTTP Header Injection', 'severity': 'HIGH', 'confidence': '65%',
         'code': 'header("Content-Disposition: attachment; filename=\"report.pdf\"");',
         'line': 8, 'file': 'download.php'},
        {'type': 'HTTP Header Injection', 'severity': 'MEDIUM', 'confidence': '55%',
         'code': 'header("Access-Control-Allow-Origin: https://example.com");',
         'line': 5, 'file': 'cors.php'},
        {'type': 'HTTP Header Injection', 'severity': 'HIGH', 'confidence': '70%',
         'code': 'setcookie("theme", "dark", time()+3600, "/", "", true, true);',
         'line': 10, 'file': 'preferences.php'},
        {'type': 'HTTP Header Injection', 'severity': 'HIGH', 'confidence': '65%',
         'code': 'header("Location: /dashboard"); exit;',
         'line': 3, 'file': 'login_success.php'},

        # ======================================================================
        # SAFE CRYPTO / HASH (8 examples)
        # ======================================================================
        {'type': 'Weak Cryptography', 'severity': 'MEDIUM', 'confidence': '65%',
         'code': '$etag = md5($content); // HTTP ETag header, not security',
         'line': 15, 'file': 'cache_handler.php'},
        {'type': 'Weak Cryptography', 'severity': 'MEDIUM', 'confidence': '60%',
         'code': '$cache_key = "item_" . md5($url . $params); // cache key generation',
         'line': 10, 'file': 'http_cache.php'},
        {'type': 'Insecure Randomness', 'severity': 'MEDIUM', 'confidence': '65%',
         'code': '$color = sprintf("#%06x", mt_rand(0, 0xFFFFFF)); // random color for UI',
         'line': 20, 'file': 'chart_colors.php'},
        {'type': 'Weak Cryptography', 'severity': 'MEDIUM', 'confidence': '55%',
         'code': '$hash = crc32($filename); // filesystem bucket distribution, not security',
         'line': 8, 'file': 'file_storage.php'},
        {'type': 'Insecure Randomness', 'severity': 'MEDIUM', 'confidence': '60%',
         'code': '$placeholder = "user_" . rand(1, 1000); // placeholder text for demo',
         'line': 25, 'file': 'demo_data.php'},
        {'type': 'Weak Cryptography', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$checksum = sha1_file($uploaded_path); // file integrity check',
         'line': 30, 'file': 'upload_handler.php'},
        {'type': 'Insecure Randomness', 'severity': 'MEDIUM', 'confidence': '65%',
         'code': 'shuffle($products); // randomize product display order',
         'line': 12, 'file': 'shop_page.php'},
        {'type': 'Weak Cryptography', 'severity': 'MEDIUM', 'confidence': '55%',
         'code': '$thumb_name = md5($original_path) . ".jpg"; // thumbnail filename',
         'line': 18, 'file': 'image_processor.php'},

        # ======================================================================
        # CONFIG / CONSTANTS (6 examples)
        # ======================================================================
        {'type': 'Hardcoded Credentials', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$db_host = "localhost"; $db_name = "myapp_db";',
         'line': 3, 'file': 'config.sample.php'},
        {'type': 'Hardcoded Credentials', 'severity': 'HIGH', 'confidence': '65%',
         'code': 'define("DB_HOST", "localhost"); define("DB_NAME", "wordpress");',
         'line': 5, 'file': 'wp-config-sample.php'},
        {'type': 'Hardcoded Credentials', 'severity': 'MEDIUM', 'confidence': '55%',
         'code': '$smtp_port = 587; $smtp_host = "smtp.example.com";',
         'line': 10, 'file': 'mail_config.example.php'},
        {'type': 'Information Disclosure', 'severity': 'MEDIUM', 'confidence': '60%',
         'code': 'define("APP_VERSION", "4.2.1"); define("API_VERSION", "v2");',
         'line': 2, 'file': 'version.php'},
        {'type': 'Hardcoded Credentials', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$default_password = "changeme"; // shown to user as hint to change password',
         'line': 15, 'file': 'install/setup.php'},
        {'type': 'Information Disclosure', 'severity': 'LOW', 'confidence': '50%',
         'code': '$debug = false; $log_level = "error";',
         'line': 8, 'file': 'config/app.php'},

        # ======================================================================
        # CUSTOM SANITIZER WRAPPERS (8 examples)
        # ======================================================================
        {'type': 'Cross-Site Scripting', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$clean_name = clean_input($raw_name); echo $clean_name;',
         'line': 10, 'file': 'display.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '75%',
         'code': '$safe_id = sanitize_id($_GET["id"]); $db->query("SELECT * FROM users WHERE id=" . $safe_id);',
         'line': 15, 'file': 'user_api.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'MEDIUM', 'confidence': '60%',
         'code': '$output = purify_html($user_content); echo $output;',
         'line': 20, 'file': 'content_display.php'},
        {'type': 'Command Injection', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$safe_path = validate_file_path($_GET["file"]); exec("cat " . $safe_path);',
         'line': 12, 'file': 'file_viewer.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '65%',
         'code': '$filtered = filter_search_input($_POST["q"]); $results = $db->query("SELECT * FROM products WHERE name LIKE \'%" . $filtered . "%\'");',
         'line': 8, 'file': 'search_handler.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'HIGH', 'confidence': '65%',
         'code': '$safe = escape_output($data); echo "<div>" . $safe . "</div>";',
         'line': 25, 'file': 'widget.php'},
        {'type': 'SQL Injection', 'severity': 'MEDIUM', 'confidence': '60%',
         'code': '$clean = $this->security->xss_clean($this->input->post("comment")); $this->db->insert("comments", ["text" => $clean]);',
         'line': 18, 'file': 'application/controllers/Comment.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'HIGH', 'confidence': '65%',
         'code': '$name = protect_xss($_POST["name"]); echo "Welcome, " . $name;',
         'line': 5, 'file': 'welcome.php'},

        # ======================================================================
        # SAFE FILE OPERATIONS (8 examples)
        # ======================================================================
        {'type': 'Path Traversal', 'severity': 'HIGH', 'confidence': '75%',
         'code': '$filename = basename($_GET["file"]); $path = "/uploads/" . $filename; if (file_exists($path)) { readfile($path); }',
         'line': 10, 'file': 'download.php'},
        {'type': 'Arbitrary File Read', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$real = realpath("themes/" . $_GET["theme"]); if (strpos($real, realpath("themes/")) === 0) { include($real); }',
         'line': 8, 'file': 'theme_loader.php'},
        {'type': 'File Inclusion', 'severity': 'HIGH', 'confidence': '80%',
         'code': '$allowed = ["header", "footer", "sidebar"]; $tpl = in_array($_GET["section"], $allowed) ? $_GET["section"] : "header"; include("parts/" . $tpl . ".php");',
         'line': 5, 'file': 'template.php'},
        {'type': 'Unsafe File Upload', 'severity': 'HIGH', 'confidence': '75%',
         'code': '$ext = strtolower(pathinfo($_FILES["file"]["name"], PATHINFO_EXTENSION)); if (in_array($ext, ["jpg","png","gif"])) { $newname = uniqid() . "." . $ext; move_uploaded_file($_FILES["file"]["tmp_name"], "uploads/" . $newname); }',
         'line': 15, 'file': 'upload_handler.php'},
        {'type': 'Path Traversal', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$doc = basename($_GET["doc"]); $full = "/var/www/docs/" . $doc; if (is_file($full) && strpos(realpath($full), "/var/www/docs/") === 0) { header("Content-Type: application/pdf"); readfile($full); }',
         'line': 20, 'file': 'serve_document.php'},
        {'type': 'Arbitrary File Write', 'severity': 'HIGH', 'confidence': '75%',
         'code': '$log_file = "/var/log/app/app.log"; file_put_contents($log_file, date("Y-m-d") . " " . $message . "\\n", FILE_APPEND);',
         'line': 12, 'file': 'logger.php'},
        {'type': 'Arbitrary File Read', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$config = parse_ini_file("/etc/myapp/config.ini"); // reading own config file',
         'line': 3, 'file': 'bootstrap.php'},
        {'type': 'File Inclusion', 'severity': 'HIGH', 'confidence': '75%',
         'code': '$controller = preg_replace("/[^a-zA-Z0-9_]/", "", $_GET["c"]); if (file_exists("controllers/" . $controller . ".php")) { require("controllers/" . $controller . ".php"); }',
         'line': 10, 'file': 'router.php'},

        # ======================================================================
        # AUTH / ACCESS CONTROL (6 examples)
        # ======================================================================
        {'type': 'Authentication Bypass', 'severity': 'HIGH', 'confidence': '65%',
         'code': 'if (!$this->auth->isLoggedIn()) { redirect("/login"); return; } $user_id = $this->auth->getUserId();',
         'line': 5, 'file': 'application/controllers/Dashboard.php'},
        {'type': 'Insecure Direct Object Reference', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$doc = Document::findOrFail($id); $this->authorize("view", $doc); return view("document", compact("doc"));',
         'line': 15, 'file': 'app/Http/Controllers/DocumentController.php'},
        {'type': 'Cross-Site Request Forgery', 'severity': 'HIGH', 'confidence': '75%',
         'code': 'if (!wp_verify_nonce($_POST["_nonce"], "update_settings")) { wp_die("Invalid nonce"); } update_option("setting", $_POST["value"]);',
         'line': 10, 'file': 'wp-content/plugins/my-plugin/settings.php'},
        {'type': 'Insecure Direct Object Reference', 'severity': 'HIGH', 'confidence': '65%',
         'code': 'if ($post->user_id !== Auth::id()) { abort(403); } $post->update($request->validated());',
         'line': 20, 'file': 'app/Http/Controllers/PostController.php'},
        {'type': 'Authentication Bypass', 'severity': 'HIGH', 'confidence': '60%',
         'code': 'if (!current_user_can("manage_options")) { wp_die("Unauthorized"); }',
         'line': 3, 'file': 'wp-content/plugins/my-plugin/admin-page.php'},
        {'type': 'Cross-Site Request Forgery', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$this->middleware("auth"); $this->middleware("verified");',
         'line': 8, 'file': 'app/Http/Controllers/AccountController.php'},

        # ======================================================================
        # SAFE SSRF (5 examples)
        # ======================================================================
        {'type': 'Server-Side Request Forgery', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$allowed = ["https://api.example.com", "https://cdn.example.com"]; $url = $_GET["api"]; if (in_array($url, $allowed)) { $data = file_get_contents($url); }',
         'line': 12, 'file': 'api_proxy.php'},
        {'type': 'Server-Side Request Forgery', 'severity': 'HIGH', 'confidence': '65%',
         'code': '$host = parse_url($_GET["url"], PHP_URL_HOST); if ($host === "api.trusted.com") { $response = file_get_contents($_GET["url"]); }',
         'line': 8, 'file': 'fetch.php'},
        {'type': 'Server-Side Request Forgery', 'severity': 'MEDIUM', 'confidence': '60%',
         'code': '$avatar_url = "https://avatars.example.com/" . urlencode($username) . ".png"; $img = file_get_contents($avatar_url);',
         'line': 15, 'file': 'avatar.php'},
        {'type': 'Server-Side Request Forgery', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$url = filter_var($_POST["webhook"], FILTER_VALIDATE_URL); $parsed = parse_url($url); if (!in_array($parsed["host"], $allowed_hosts)) { die("Invalid host"); }',
         'line': 20, 'file': 'webhook.php'},
        {'type': 'Server-Side Request Forgery', 'severity': 'MEDIUM', 'confidence': '55%',
         'code': 'curl_setopt($ch, CURLOPT_URL, "https://api.stripe.com/v1/charges"); // fixed API endpoint',
         'line': 10, 'file': 'payment.php'},

        # ======================================================================
        # SAFE DESERIALIZATION (5 examples)
        # ======================================================================
        {'type': 'Insecure Deserialization', 'severity': 'CRITICAL', 'confidence': '80%',
         'code': '$data = json_decode($request->getContent(), true); // JSON, not PHP serialize',
         'line': 10, 'file': 'api/handler.php'},
        {'type': 'Insecure Deserialization', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$settings = unserialize($row["settings"], ["allowed_classes" => false]); // restricted unserialize',
         'line': 15, 'file': 'settings_loader.php'},
        {'type': 'Insecure Deserialization', 'severity': 'CRITICAL', 'confidence': '85%',
         'code': '$cache_data = igbinary_unserialize(file_get_contents($cache_file)); // from local cache file, not user input',
         'line': 20, 'file': 'cache/driver.php'},
        {'type': 'Insecure Deserialization', 'severity': 'HIGH', 'confidence': '75%',
         'code': '$config = yaml_parse_file("/etc/app/config.yml"); // YAML from config file, not user input',
         'line': 5, 'file': 'config_loader.php'},
        {'type': 'Insecure Deserialization', 'severity': 'CRITICAL', 'confidence': '80%',
         'code': '$msg = json_decode(base64_decode($jwt_payload), true); // JWT payload is JSON',
         'line': 25, 'file': 'auth/jwt.php'},

        # ======================================================================
        # RACE CONDITION FPs (5 examples)
        # ======================================================================
        {'type': 'Race Condition', 'severity': 'MEDIUM', 'confidence': '65%',
         'code': 'if (file_exists($cache_file)) { $data = file_get_contents($cache_file); } // read-only cache check',
         'line': 10, 'file': 'cache.php'},
        {'type': 'Race Condition', 'severity': 'MEDIUM', 'confidence': '60%',
         'code': 'if (is_dir($upload_dir)) { $files = scandir($upload_dir); } // directory listing',
         'line': 15, 'file': 'gallery.php'},
        {'type': 'Race Condition', 'severity': 'MEDIUM', 'confidence': '65%',
         'code': 'clearstatcache(); if (file_exists($lock_file)) { sleep(1); continue; } // proper lock check with cache clear',
         'line': 20, 'file': 'queue_worker.php'},
        {'type': 'Race Condition', 'severity': 'LOW', 'confidence': '50%',
         'code': '$size = filesize($log_file); if ($size > 10485760) { error_log("Log file large"); } // monitoring only',
         'line': 8, 'file': 'monitor.php'},
        {'type': 'Race Condition', 'severity': 'MEDIUM', 'confidence': '55%',
         'code': '$mtime = filemtime($template); if ($mtime > $cached_time) { $compiled = compile_template($template); } // template cache invalidation',
         'line': 12, 'file': 'template_engine.php'},

        # ======================================================================
        # LOG / INFO DISCLOSURE FPs (6 examples)
        # ======================================================================
        {'type': 'Information Disclosure', 'severity': 'MEDIUM', 'confidence': '55%',
         'code': 'error_log("[" . date("Y-m-d H:i:s") . "] Request: " . $_SERVER["REQUEST_URI"]);',
         'line': 5, 'file': 'middleware/logging.php'},
        {'type': 'Log Injection', 'severity': 'MEDIUM', 'confidence': '60%',
         'code': '$logger->info("User action", ["user_id" => $user->id, "action" => $action]); // structured logging',
         'line': 20, 'file': 'app/Services/AuditService.php'},
        {'type': 'Information Disclosure', 'severity': 'LOW', 'confidence': '45%',
         'code': 'if ($debug) { echo "<!-- Render time: " . (microtime(true) - $start) . "s -->"; }',
         'line': 100, 'file': 'footer.php'},
        {'type': 'Information Disclosure', 'severity': 'MEDIUM', 'confidence': '50%',
         'code': 'header("X-Request-ID: " . $request_id); // tracing header',
         'line': 3, 'file': 'middleware/tracing.php'},
        {'type': 'Log Injection', 'severity': 'MEDIUM', 'confidence': '65%',
         'code': 'syslog(LOG_INFO, "Login successful for user ID: " . (int)$user_id);',
         'line': 25, 'file': 'auth_handler.php'},
        {'type': 'Information Disclosure', 'severity': 'LOW', 'confidence': '40%',
         'code': 'trigger_error("Cache miss for key: " . md5($cache_key), E_USER_NOTICE);',
         'line': 30, 'file': 'cache_driver.php'},

        # ======================================================================
        # XSS FALSE POSITIVES (10 examples)
        # ======================================================================
        {'type': 'Cross-Site Scripting', 'severity': 'HIGH', 'confidence': '65%',
         'code': 'echo "<img src=\"/avatars/" . (int)$user_id . ".jpg\" alt=\"avatar\">";',
         'line': 15, 'file': 'profile_card.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'MEDIUM', 'confidence': '55%',
         'code': 'echo $twig->render("profile.html.twig", ["user" => $user]); // Twig auto-escapes',
         'line': 20, 'file': 'src/Controller/ProfileController.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'MEDIUM', 'confidence': '50%',
         'code': 'echo "<meta name=\"description\" content=\"" . htmlspecialchars($desc) . "\">";',
         'line': 8, 'file': 'head.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'HIGH', 'confidence': '60%',
         'code': 'header("Content-Type: application/json"); echo json_encode(["status" => $status, "data" => $result]);',
         'line': 5, 'file': 'api/endpoint.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'MEDIUM', 'confidence': '55%',
         'code': 'echo "Order #" . (int)$order_id . " - Total: $" . number_format($total, 2);',
         'line': 30, 'file': 'order_confirmation.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'HIGH', 'confidence': '65%',
         'code': 'echo nl2br(htmlspecialchars($comment->body, ENT_QUOTES, "UTF-8"));',
         'line': 40, 'file': 'comments.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'MEDIUM', 'confidence': '50%',
         'code': 'echo date("Y-m-d", strtotime($date_input)); // date parsing, not direct output',
         'line': 12, 'file': 'calendar.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'HIGH', 'confidence': '60%',
         'code': '<?php echo esc_textarea($content); ?></textarea>',
         'line': 18, 'file': 'wp-content/themes/theme/editor.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'MEDIUM', 'confidence': '55%',
         'code': 'echo "<a href=\"mailto:" . filter_var($email, FILTER_SANITIZE_EMAIL) . "\">" . htmlspecialchars($name) . "</a>";',
         'line': 22, 'file': 'contact.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'HIGH', 'confidence': '65%',
         'code': 'echo sprintf("<td>%s</td><td>%d</td>", htmlspecialchars($product_name), $quantity);',
         'line': 35, 'file': 'order_table.php'},

        # ======================================================================
        # PATH TRAVERSAL SAFE (5 examples)
        # ======================================================================
        {'type': 'Path Traversal', 'severity': 'HIGH', 'confidence': '75%',
         'code': '$name = str_replace(["../", "..\\\\", "..", "/", "\\\\"], "", $_GET["name"]); include("modules/" . $name . ".php");',
         'line': 5, 'file': 'module_loader.php'},
        {'type': 'Path Traversal', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$page = basename($_GET["page"], ".php"); if (ctype_alnum($page)) { include("pages/" . $page . ".php"); }',
         'line': 8, 'file': 'page_router.php'},
        {'type': 'Arbitrary File Read', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$img = "images/" . preg_replace("/[^a-zA-Z0-9._-]/", "", $_GET["img"]); if (file_exists($img)) { readfile($img); }',
         'line': 10, 'file': 'serve_image.php'},
        {'type': 'Path Traversal', 'severity': 'HIGH', 'confidence': '65%',
         'code': '$theme = preg_replace("/[^a-z0-9_-]/i", "", $_COOKIE["theme"]); include("themes/" . $theme . "/style.css");',
         'line': 3, 'file': 'theme.php'},
        {'type': 'File Inclusion', 'severity': 'HIGH', 'confidence': '75%',
         'code': '$map = ["home" => "home.php", "about" => "about.php", "contact" => "contact.php"]; $page = $map[$_GET["p"]] ?? "home.php"; include("views/" . $page);',
         'line': 5, 'file': 'router.php'},

        # ======================================================================
        # MISCELLANEOUS FPs (8 examples)
        # ======================================================================
        {'type': 'XML External Entity', 'severity': 'HIGH', 'confidence': '75%',
         'code': 'libxml_disable_entity_loader(true); $xml = simplexml_load_string($body);',
         'line': 10, 'file': 'xml_parser.php'},
        {'type': 'XML External Entity', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$doc = new DOMDocument(); $doc->loadXML($input, LIBXML_NOENT | LIBXML_DTDLOAD); // XXE protections enabled',
         'line': 15, 'file': 'soap_handler.php'},
        {'type': 'Mass Assignment', 'severity': 'HIGH', 'confidence': '80%',
         'code': '$user->fill($request->only(["name", "email"])); $user->save(); // only whitelisted fields',
         'line': 20, 'file': 'app/Http/Controllers/UserController.php'},
        {'type': 'Mass Assignment', 'severity': 'HIGH', 'confidence': '75%',
         'code': '$post = new Post(); $post->title = $request->input("title"); $post->body = $request->input("body"); $post->save(); // explicit assignment',
         'line': 25, 'file': 'app/Http/Controllers/PostController.php'},
        {'type': 'LDAP Injection', 'severity': 'HIGH', 'confidence': '70%',
         'code': '$username = ldap_escape($_POST["user"], "", LDAP_ESCAPE_FILTER); $result = ldap_search($ldap, $base, "(uid=$username)");',
         'line': 10, 'file': 'ldap_auth.php'},
        {'type': 'Regular Expression DoS', 'severity': 'MEDIUM', 'confidence': '60%',
         'code': '$clean = preg_replace("/[^a-zA-Z0-9 ]/", "", $input); // simple character class, no backtracking',
         'line': 5, 'file': 'sanitize.php'},
        {'type': 'Template Injection', 'severity': 'HIGH', 'confidence': '70%',
         'code': 'echo $twig->render("email_template.html.twig", ["name" => htmlspecialchars($name)]); // Twig sandboxed + escaped',
         'line': 15, 'file': 'mailer.php'},
        {'type': 'Type Juggling', 'severity': 'HIGH', 'confidence': '75%',
         'code': 'if (hash_equals($stored_token, $_POST["csrf_token"])) { process_form(); } // timing-safe comparison',
         'line': 10, 'file': 'form_handler.php'},
    ]


def get_extended_tp_examples():
    """Return additional TP training examples for variety."""
    return [
        # Additional TP patterns not covered in base training data
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '85%',
         'code': '$db->query("SELECT * FROM users WHERE username=\'" . $_POST["user"] . "\' AND password=\'" . $_POST["pass"] . "\'");',
         'line': 10, 'file': 'login.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'HIGH', 'confidence': '80%',
         'code': 'echo "<div class=\'msg\'>" . $_POST["message"] . "</div>";',
         'line': 25, 'file': 'guestbook.php'},
        {'type': 'Command Injection', 'severity': 'CRITICAL', 'confidence': '90%',
         'code': '$output = shell_exec("ping -c 3 " . $_GET["host"]);',
         'line': 8, 'file': 'network_tools.php'},
        {'type': 'File Inclusion', 'severity': 'HIGH', 'confidence': '80%',
         'code': 'require_once($_GET["controller"] . ".php");',
         'line': 5, 'file': 'autoloader.php'},
        {'type': 'Server-Side Request Forgery', 'severity': 'HIGH', 'confidence': '75%',
         'code': '$content = file_get_contents("http://" . $_POST["domain"] . "/api/data");',
         'line': 12, 'file': 'aggregator.php'},
        {'type': 'Path Traversal', 'severity': 'HIGH', 'confidence': '80%',
         'code': '$data = file_get_contents("../../data/" . $_GET["file"]);',
         'line': 7, 'file': 'reader.php'},
        {'type': 'Code Injection', 'severity': 'CRITICAL', 'confidence': '95%',
         'code': 'preg_replace("/(.+)/e", $_POST["replace"], $subject); // e modifier = eval',
         'line': 15, 'file': 'regex_tool.php'},
        {'type': 'Insecure Deserialization', 'severity': 'CRITICAL', 'confidence': '90%',
         'code': '$obj = unserialize(base64_decode($_POST["data"]));',
         'line': 20, 'file': 'import.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '80%',
         'code': 'mysql_query("INSERT INTO comments (body) VALUES (\'" . $_POST["comment"] . "\')");',
         'line': 30, 'file': 'comment.php'},
        {'type': 'Open Redirect', 'severity': 'HIGH', 'confidence': '85%',
         'code': 'header("Location: " . $_REQUEST["return_url"]); exit;',
         'line': 5, 'file': 'auth_callback.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'HIGH', 'confidence': '75%',
         'code': '?><script>var user = "<?= $_GET["name"] ?>";</script>',
         'line': 35, 'file': 'profile_page.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '85%',
         'code': '$result = pg_query("SELECT * FROM orders WHERE status=\'" . $_GET["status"] . "\'");',
         'line': 18, 'file': 'orders.php'},
        {'type': 'Arbitrary File Write', 'severity': 'HIGH', 'confidence': '80%',
         'code': 'file_put_contents($_POST["filename"], $_POST["content"]);',
         'line': 10, 'file': 'editor.php'},
        {'type': 'HTTP Header Injection', 'severity': 'HIGH', 'confidence': '85%',
         'code': 'header("Location: " . $_GET["redirect"] . "\\r\\nSet-Cookie: admin=1");',
         'line': 3, 'file': 'redirect.php'},
        {'type': 'Cross-Site Scripting', 'severity': 'HIGH', 'confidence': '80%',
         'code': 'echo "Search results for: <b>" . $_GET["q"] . "</b>";',
         'line': 12, 'file': 'search_results.php'},
        {'type': 'Command Injection', 'severity': 'CRITICAL', 'confidence': '85%',
         'code': 'exec("convert " . $_FILES["image"]["tmp_name"] . " -resize 100x100 " . $_POST["output"]);',
         'line': 22, 'file': 'image_resize.php'},
        {'type': 'SQL Injection', 'severity': 'HIGH', 'confidence': '80%',
         'code': '$sql = "UPDATE users SET role=\'" . $_POST["role"] . "\' WHERE id=" . $_POST["uid"]; $db->exec($sql);',
         'line': 15, 'file': 'admin/user_edit.php'},
        {'type': 'Insecure Deserialization', 'severity': 'CRITICAL', 'confidence': '85%',
         'code': '$session = unserialize($_COOKIE["session_data"]);',
         'line': 3, 'file': 'session_handler.php'},
        {'type': 'XML External Entity', 'severity': 'HIGH', 'confidence': '80%',
         'code': '$xml = new SimpleXMLElement($_POST["xml_data"]); // no entity protection',
         'line': 10, 'file': 'import_xml.php'},
        {'type': 'Arbitrary File Read', 'severity': 'HIGH', 'confidence': '75%',
         'code': 'echo file_get_contents("/var/www/" . $_GET["path"]);',
         'line': 8, 'file': 'view_source.php'},
    ]
